### ISSUE TITLE
Syntax error when running under Python3.5

### ISSUE THREAD

**Issue by PaulVanNiekerk** [orzih/mkdocs-with-pdf#45]
It looks like the f"..." syntax is not supported in Python3.5.
Running mkdocs build gives:

Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/mkdocs/__main__.py", line 152, in build_command
    build.build(config.load_config(**kwargs), dirty=not clean)
  File "/usr/local/lib/python3.5/dist-packages/mkdocs/config/base.py", line 197, in load_config
    errors, warnings = cfg.validate()
  File "/usr/local/lib/python3.5/dist-packages/mkdocs/config/base.py", line 107, in validate
    run_failed, run_warnings = self._validate()
  File "/usr/local/lib/python3.5/dist-packages/mkdocs/config/base.py", line 62, in _validate
    self[key] = config_option.validate(value)
  File "/usr/local/lib/python3.5/dist-packages/mkdocs/config/config_options.py", line 131, in validate
    return self.run_validation(value)
  File "/usr/local/lib/python3.5/dist-packages/mkdocs/config/config_options.py", line 609, in run_validation
    plgins[item] = self.load_plugin(item, cfg)
  File "/usr/local/lib/python3.5/dist-packages/mkdocs/config/config_options.py", line 617, in load_plugin
    Plugin = self.installed_plugins[name].load()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2447, in load
    return self.resolve()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2453, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/dist-packages/mkdocs_with_pdf/plugin.py", line 68
    f'(set environment variable {env_name} to 1 to enable)'
    ^
SyntaxError: invalid syntax

**Comment by orzih** [comment]
Thank you for your report.
Sorry, I did never run it on 3.5.

As you pointed out, f-strings is not supported in 3.5.
https://www.python.org/dev/peps/pep-0498/

Can I drop support for Python 3.5?
https://www.python.org/downloads/release/python-3510/

**Comment by orzih** [comment]
This issue was fixed in v0.8.3. Please check it.

However, support for Python 3.5 will end in the near future.

**Comment by PaulVanNiekerk** [comment]
It works now. Thanks for fixing!
