### ISSUE TITLE
Overlapped text in rendered PDF

### ISSUE THREAD

**Issue by darkonl** [orzih/mkdocs-with-pdf#52]
### Current Behavior
This is a piece of rendered PDF file:

![imagen](https://user-images.githubusercontent.com/12811094/107963133-10160700-6fa8-11eb-9aa4-2dabfb9c9fb4.png)

The rendered file text seems to be overlapped.

### Context (Environment)
- Python v3.8.7
- mkdocs-with-pdf v0.8.3
- WeasyPrint v52.2

My mkdocs.yml plugins config:
```
plugins:
  - search
  - mermaid2
  - markdownextradata
  - with-pdf
```

**Comment by darkonl** [comment]
I uninstalled and installed again all dependencies to run my project, and I found that text is displayed correctly, but now the titles have the same issue than before:

![imagen](https://user-images.githubusercontent.com/12811094/107977037-bf5bd980-6fba-11eb-8caf-d8f1dfe076a3.png)

**Comment by orzih** [comment]
Hi @darkonl
What theme(or custom css) are you using?

Please try build with `debug_html` option of this plugin, and check these styles.

Note: mermaid.js does not work well with WeasyPrint. see #34.

**Comment by darkonl** [comment]
I'm using `mkdocs-material`.

The output in `ebuga_html` is:

```
$ mkdocs serve
INFO    -  Building documentation...
INFO    -  MERMAID2  - Initialization arguments: {}
INFO    -  MERMAID2  - Explicit mermaid javascript library:
   https://unpkg.com/mermaid@8.6.4/dist/mermaid.min.js
INFO    -  Cleaning site directory
INFO    -  MERMAID2  - Found superfences config: {'custom_fences': [{'name': 'mermaid', 'class': 'mermaid', 'format': <function fence_div_format at 0x0000029EA64CA1F0>}]}
INFO    -  MERMAID2  - Page 'Method 1': found 2 diagrams, adding scripts
INFO    -  MERMAID2  - Page 'Method 10': found 2 diagrams, adding scripts
INFO    -  MERMAID2  - Page 'Method 11': found 2 diagrams, adding scripts
INFO    -  MERMAID2  - Page 'Method 12': found 2 diagrams, adding scripts
INFO    -  MERMAID2  - Page 'Method 13': found 2 diagrams, adding scripts
INFO    -  MERMAID2  - Page 'Method 14': found 2 diagrams, adding scripts
INFO    -  MERMAID2  - Page 'Method 15': found 2 diagrams, adding scripts
INFO    -  MERMAID2  - Page 'Method 16': found 2 diagrams, adding scripts
INFO    -  MERMAID2  - Page 'Method 17': found 2 diagrams, adding scripts
INFO    -  MERMAID2  - Page 'Method 18': found 2 diagrams, adding scripts
INFO    -  MERMAID2  - Page 'Method 19': found 2 diagrams, adding scripts
INFO    -  MERMAID2  - Page 'Method 2': found 2 diagrams, adding scripts
INFO    -  MERMAID2  - Page 'Method 3': found 2 diagrams, adding scripts
INFO    -  MERMAID2  - Page 'Method 4': found 2 diagrams, adding scripts
INFO    -  MERMAID2  - Page 'Method 5': found 2 diagrams, adding scripts
INFO    -  MERMAID2  - Page 'Method 6': found 2 diagrams, adding scripts
INFO    -  MERMAID2  - Page 'Method 7': found 2 diagrams, adding scripts
INFO    -  MERMAID2  - Page 'Method 8': found 2 diagrams, adding scripts
INFO    -  MERMAID2  - Page 'Method 9': found 2 diagrams, adding scripts
INFO    -  Number headings up to level 3.
INFO    -  Generate a table of contents up to heading level 2.
INFO    -  Template variables:
INFO    -    {'author': 'Dario Perez (Amphos 21)',
INFO    -     'copyright': None,
INFO    -     'cover_logo': None,
INFO    -     'cover_subtitle': 'A database management tool for ThermoChimie',
INFO    -     'cover_title': 'XCheck Tool',
INFO    -     'cte': {'R': '$R=8.3144598 J\\cdot mol^{-1}\\cdot K^{-1}$',
INFO    -             'RTln10': '$RTln(10)$',
INFO    -             'RTln10_value': '$RTln(10)=5.70800756783$ at $T=298.15 K$'},
INFO    -     'math': {'gf_fromGr': '$\\Delta_fG^0_m = \\Delta_{r,p}G^0_m +  '
INFO    -                           '\\sum\\limits_{reactants}\\nu_r\\Delta_{f,r}G^0_m$',
INFO    -              'gf_fromHS': '$\\Delta_fG^0_m = \\Delta_fH^0_m - T(S^0_m + '
INFO    -                           '\\frac{z}{2}xS^0_{m,H_2(g)} - '
INFO    -                           '\\sum\\limits_{i}\\frac{\\nu_i}{\\nu_{i,ref}S^0_{m,i}})$',
INFO    -              'gr_fromGf': '$\\Delta_rG^0_m = \\Delta_{f,p}G^0_m -  '
INFO    -                           '\\sum\\limits_{reactants}\\nu_r\\Delta_{f,r}G^0_m$',
INFO    -              'gr_fromHS': '$\\Delta_rG^0_m = \\Delta_rH^0_m - T\\Delta_rS^0_m$',
INFO    -              'gr_fromLogk': '$\\Delta_rG^0_m = -RTln(10)log_{10}K^0_r$',
INFO    -              'hf_fromGS': '$\\Delta_fH^0_m = \\Delta_fG^0_m + T(S^0_m + '
INFO    -                           '\\frac{z}{2}xS^0_{m,H_2(g)} - '
INFO    -                           '\\sum\\limits_{i}\\frac{\\nu_i}{\\nu_{i,ref}S^0_{m,i}})$',
INFO    -              'hf_fromHr': '$\\Delta_fH^0_m = \\Delta_{r,p}H^0_m +  '
INFO    -                           '\\sum\\limits_{reactants}\\nu_r\\Delta_{f,r}H^0_m$',
INFO    -              'hr_fromGS': '$\\Delta_rH^0_m = \\Delta_rG^0_m + T\\Delta_rS^0_m$',
INFO    -              'hr_fromHf': '$\\Delta_rH^0_m = \\Delta_{f,p}H^0_m -  '
INFO    -                           '\\sum\\limits_{reactants}\\nu_r\\Delta_{f,r}H^0_m$',
INFO    -              'logk_fromGr': '$log_{10}K^0_r = -\\frac{\\Delta_rG^0_m}{RTln(10)}$',
INFO    -              'sf_fromGH': '$S^0_m = \\frac{\\Delta_fH^0_m - \\Delta_fG^0_m}{T} - '
INFO    -                           '\\left( \\frac{z}{2}xS^0_{m,H_2(g)} - '
INFO    -                           '\\sum\\limits_{i}\\frac{\\nu_i}{\\nu_{i,ref}S^0_{m,i}} '
INFO    -                           '\\right)$',
INFO    -              'sf_fromSr': '$S^0_m = \\Delta_{r}S^0_m +  '
INFO    -                           '\\sum\\limits_{reactants}\\nu_rS^0_{m,r}$',
INFO    -              'sr_fromGH': '$\\Delta_rS^0_m = \\frac{\\Delta_rH^0_m - '
INFO    -                           '\\Delta_rG^0_m}{T}$',
INFO    -              'sr_fromSf': '$\\Delta_rS^0_m = S^0_m -  '
INFO    -                           '\\sum\\limits_{reactants}\\nu_rS^0_{m,r}$'},
INFO    -     'now': datetime.datetime(2021, 2, 16, 9, 32, 59, 907990),
INFO    -     'repo_url': '',
INFO    -     'sit': {'cl': '$\\varepsilon(M^+,Cl^-)$',
INFO    -             'clo4': '$\\varepsilon(M^+,ClO^-_4)$',
INFO    -             'na': '$\\varepsilon(Na^+,X^-)$',
INFO    -             'no3': '$\\varepsilon(M^+,NO^-_3)$'},
INFO    -     'site_url': 'http://127.0.0.1:8000/',
INFO    -     'thermo': {'cf': '$C^0_{p,m}$',
INFO    -                'cr': '$\\Delta_rC^0_{p,m}$',
INFO    -                'gf': '$\\Delta_fG^0_m$',
INFO    -                'gr': '$\\Delta_rG^0_m$',
INFO    -                'hf': '$\\Delta_fH^0_m$',
INFO    -                'hr': '$\\Delta_rH^0_m$',
INFO    -                'logk': '$log_{10}K^0_r$',
INFO    -                'reff': '$R_{i,eff}$',
INFO    -                'ri': '$R_i$',
INFO    -                'sf': '$S^0_m$',
INFO    -                'sr': '$\\Delta_rS^0_m$',
INFO    -                'vm': '$V_m$'}}
INFO    -  Generate a cover page with "default_cover.html.j2".
INFO    -  Converting <img> alignment(workaround).
ERROR   -  Missing 17 link(s):
WARNING -    | #user-guide/calc-routes/:method-1
WARNING -    | #user-guide/glossary.md/:xcheck-tool-thermochimie-releases-compatibility
WARNING -    | #user-guide/menu/:import
WARNING -    | #user-guide/menu/file/:bibliographic-reference
WARNING -    | #user-guide/menu/tools/:JSON-comparer
WARNING -    | #user-guide/menu/tools/:JSON-to-excel-converter
WARNING -    | /docs/user-guide/menu/file.md#import
WARNING -    | /glossary#data-source-versions
WARNING -    | /glossary/#thermochimie-historic-releases
WARNING -    | /glossary/#xcheck-tool-thermochimie-releases-compatibility
WARNING -    | /user-guide/menu#loaded-source
WARNING -    | /user-guide/menu/automation
WARNING -    | /user-guide/menu/edition
WARNING -    | /user-guide/menu/file
WARNING -    | /user-guide/menu/file/#import
WARNING -    | /user-guide/menu/help
WARNING -    | /user-guide/menu/tools
INFO    -    | --- found anchors:
INFO    -    | #.:
INFO    -    | #.:introduction
INFO    -    | #.:the-xcheck-tool
INFO    -    | #.:xcheck-tool-v50
INFO    -    | #KN2XA4DPOJ2GS3THEBSG6Y3VNVSW45DBORUW63Q/
INFO    -    | #KN2XA4DPOJ2GS3THEBSG6Y3VNVSW45DBORUW63Q/:
INFO    -    | #KN2XA4DPOJ2GS3THEBSG6Y3VNVSW45DBORUW63Q/INQWYY3VNRQXI2LPNYQHE33VORSXG/
INFO    -    | #KN2XA4DPOJ2GS3THEBSG6Y3VNVSW45DBORUW63Q/INQWYY3VNRQXI2LPNYQHE33VORSXG/:
INFO    -    | #KVZWK4RAM52WSZDF/
INFO    -    | #KVZWK4RAM52WSZDF/:
INFO    -    | #KVZWK4RAM52WSZDF/INQWYY3VNRQXI33S/
INFO    -    | #KVZWK4RAM52WSZDF/INQWYY3VNRQXI33S/:
INFO    -    | #KVZWK4RAM52WSZDF/IRQXIYJAMNXW443VNR2GC5DJN5XA/
INFO    -    | #KVZWK4RAM52WSZDF/IRQXIYJAMNXW443VNR2GC5DJN5XA/:
INFO    -    | #KVZWK4RAM52WSZDF/IVSGS5DPOI/
INFO    -    | #KVZWK4RAM52WSZDF/IVSGS5DPOI/:
INFO    -    | #KVZWK4RAM52WSZDF/JVSW45I/
INFO    -    | #KVZWK4RAM52WSZDF/JVSW45I/:
INFO    -    | #about/:
INFO    -    | #about/:about-the-xcheck-tool-v50
INFO    -    | #author
INFO    -    | #contact/:
INFO    -    | #contact/:contact-us
INFO    -    | #copyright
INFO    -    | #doc-cover
INFO    -    | #doc-toc
INFO    -    | #glossary/:
INFO    -    | #glossary/:data-source-versions
INFO    -    | #glossary/:fn:1
INFO    -    | #glossary/:fnref:1
INFO    -    | #glossary/:glossary
INFO    -    | #glossary/:species-types
INFO    -    | #glossary/:thermochimie-historic-releases
INFO    -    | #glossary/:xcheck-tool-thermochimie-releases-compatibility
INFO    -    | #installation/:
INFO    -    | #installation/:fn1
INFO    -    | #installation/:fn2
INFO    -    | #installation/:fn3
INFO    -    | #installation/:installation-system-requirements
INFO    -    | #installation/:vertical-1
INFO    -    | #references/:
INFO    -    | #references/:bibliographic-references
INFO    -    | #references/:editing-references
INFO    -    | #references/:load-bibliographic-records
INFO    -    | #user-guide/automation/:
INFO    -    | #user-guide/automation/:automation
INFO    -    | #user-guide/automation/:consulting-automation-results
INFO    -    | #user-guide/automation/:description
INFO    -    | #user-guide/automation/:exporting-automation-results
INFO    -    | #user-guide/automation/:filtering-data
INFO    -    | #user-guide/automation/:perform-automation
INFO    -    | #user-guide/calc-routes/:
INFO    -    | #user-guide/calc-routes/:calculation-routes
INFO    -    | #user-guide/calc-routes/:fn:1
INFO    -    | #user-guide/calc-routes/:fnref:1
INFO    -    | #user-guide/calculator/:
INFO    -    | #user-guide/calculator/:calculator
INFO    -    | #user-guide/calculator/calc0-load-data/:
INFO    -    | #user-guide/calculator/calc0-load-data/:load-version
INFO    -    | #user-guide/calculator/calc1-load-species/:
INFO    -    | #user-guide/calculator/calc1-load-species/:load-existing-species-in-data-source
INFO    -    | #user-guide/calculator/calc1-load-species/:load-new-species
INFO    -    | #user-guide/calculator/calc1-load-species/:load-species
INFO    -    | #user-guide/calculator/calc2-reaction/:
INFO    -    | #user-guide/calculator/calc2-reaction/:automatically
INFO    -    | #user-guide/calculator/calc2-reaction/:build-reaction
INFO    -    | #user-guide/calculator/calc2-reaction/:clear-reaction
INFO    -    | #user-guide/calculator/calc2-reaction/:manually
INFO    -    | #user-guide/calculator/calc2-reaction/:remove-reactants
INFO    -    | #user-guide/calculator/calc2-reaction/:set-reaction
INFO    -    | #user-guide/calculator/calc3-calculate/:
INFO    -    | #user-guide/calculator/calc3-calculate/:calculate
INFO    -    | #user-guide/calculator/calc3-calculate/:clear-calculations
INFO    -    | #user-guide/calculator/calc3-calculate/:clear-input-data
INFO    -    | #user-guide/calculator/calc3-calculate/:compare-data
INFO    -    | #user-guide/calculator/calc3-calculate/:input-data
INFO    -    | #user-guide/calculator/calc3-calculate/:perform-calculations
INFO    -    | #user-guide/calculator/calc4-thermodynamics/:
INFO    -    | #user-guide/calculator/calc4-thermodynamics/:consult-master-species-data
INFO    -    | #user-guide/calculator/calc4-thermodynamics/:create-a-new-master-species
INFO    -    | #user-guide/calculator/calc4-thermodynamics/:edit-thermodynamic-data-of-master-species
INFO    -    | #user-guide/calculator/calc4-thermodynamics/:editing-thermodynamics-from-reactant
INFO    -    | #user-guide/calculator/calc4-thermodynamics/:reactants-manager
INFO    -    | #user-guide/calculator/calc4-thermodynamics/:reset-master-species-data
INFO    -    | #user-guide/calculator/calc4-thermodynamics/:thermodynamic-data-used-in-calculations
INFO    -    | #user-guide/calculator/calc5-original/:
INFO    -    | #user-guide/calculator/calc5-original/:additional-information
INFO    -    | #user-guide/calculator/calc5-original/:original-data
INFO    -    | #user-guide/calculator/calc5-original/:selected-version
INFO    -    | #user-guide/calculator/calc5-original/:thermodynamics
INFO    -    | #user-guide/comparison-criteria/:
INFO    -    | #user-guide/comparison-criteria/:comparison-criteria
INFO    -    | #user-guide/consultation/cons0-routes/:
INFO    -    | #user-guide/consultation/cons0-routes/:additional-options
INFO    -    | #user-guide/consultation/cons0-routes/:consulting-data
INFO    -    | #user-guide/consultation/cons0-routes/:consulting-species-by-selected-data
INFO    -    | #user-guide/consultation/cons0-routes/:exporting-data
INFO    -    | #user-guide/consultation/cons0-routes/:filtering-data
INFO    -    | #user-guide/consultation/cons1-param/:
INFO    -    | #user-guide/consultation/cons1-param/:additional-options
INFO    -    | #user-guide/consultation/cons1-param/:consulting-data
INFO    -    | #user-guide/consultation/cons1-param/:consulting-species-by-thermodynamic-data
INFO    -    | #user-guide/consultation/cons1-param/:exporting-data
INFO    -    | #user-guide/consultation/cons1-param/:filtering-data
INFO    -    | #user-guide/consultation/cons2-elements/:
INFO    -    | #user-guide/consultation/cons2-elements/:additional-options
INFO    -    | #user-guide/consultation/cons2-elements/:consulting-data
INFO    -    | #user-guide/consultation/cons2-elements/:consulting-species-by-elements
INFO    -    | #user-guide/consultation/cons2-elements/:consulting-species-information
INFO    -    | #user-guide/consultation/cons2-elements/:exporting-data
INFO    -    | #user-guide/consultation/cons2-elements/:filtering-data
INFO    -    | #user-guide/consultation/cons3-statistics/:
INFO    -    | #user-guide/consultation/cons3-statistics/:additional-options
INFO    -    | #user-guide/consultation/cons3-statistics/:consulting-data
INFO    -    | #user-guide/consultation/cons3-statistics/:exporting-data
INFO    -    | #user-guide/consultation/cons3-statistics/:filtering-data
INFO    -    | #user-guide/consultation/cons3-statistics/:general-statistics
INFO    -    | #user-guide/consultation/cons3-statistics/:species-by-selected-data-set
INFO    -    | #user-guide/consultation/cons3-statistics/:species-state
INFO    -    | #user-guide/consultation/cons3-statistics/:species-type
INFO    -    | #user-guide/consultation/methods/m1/:
INFO    -    | #user-guide/consultation/methods/m1/:diagram
INFO    -    | #user-guide/consultation/methods/m1/:equations
INFO    -    | #user-guide/consultation/methods/m1/:method-1
INFO    -    | #user-guide/consultation/methods/m10/:
INFO    -    | #user-guide/consultation/methods/m10/:diagram
INFO    -    | #user-guide/consultation/methods/m10/:equations
INFO    -    | #user-guide/consultation/methods/m10/:method-10
INFO    -    | #user-guide/consultation/methods/m11/:
INFO    -    | #user-guide/consultation/methods/m11/:diagram
INFO    -    | #user-guide/consultation/methods/m11/:equations
INFO    -    | #user-guide/consultation/methods/m11/:method-11
INFO    -    | #user-guide/consultation/methods/m12/:
INFO    -    | #user-guide/consultation/methods/m12/:diagram
INFO    -    | #user-guide/consultation/methods/m12/:equations
INFO    -    | #user-guide/consultation/methods/m12/:method-12
INFO    -    | #user-guide/consultation/methods/m13/:
INFO    -    | #user-guide/consultation/methods/m13/:diagram
INFO    -    | #user-guide/consultation/methods/m13/:equations
INFO    -    | #user-guide/consultation/methods/m13/:method-13
INFO    -    | #user-guide/consultation/methods/m14/:
INFO    -    | #user-guide/consultation/methods/m14/:diagram
INFO    -    | #user-guide/consultation/methods/m14/:equations
INFO    -    | #user-guide/consultation/methods/m14/:method-14
INFO    -    | #user-guide/consultation/methods/m15/:
INFO    -    | #user-guide/consultation/methods/m15/:diagram
INFO    -    | #user-guide/consultation/methods/m15/:equations
INFO    -    | #user-guide/consultation/methods/m15/:method-15
INFO    -    | #user-guide/consultation/methods/m16/:
INFO    -    | #user-guide/consultation/methods/m16/:diagram
INFO    -    | #user-guide/consultation/methods/m16/:equations
INFO    -    | #user-guide/consultation/methods/m16/:method-16
INFO    -    | #user-guide/consultation/methods/m17/:
INFO    -    | #user-guide/consultation/methods/m17/:diagram
INFO    -    | #user-guide/consultation/methods/m17/:equations
INFO    -    | #user-guide/consultation/methods/m17/:method-17
INFO    -    | #user-guide/consultation/methods/m18/:
INFO    -    | #user-guide/consultation/methods/m18/:diagram
INFO    -    | #user-guide/consultation/methods/m18/:equations
INFO    -    | #user-guide/consultation/methods/m18/:method-18
INFO    -    | #user-guide/consultation/methods/m19/:
INFO    -    | #user-guide/consultation/methods/m19/:diagram
INFO    -    | #user-guide/consultation/methods/m19/:equations
INFO    -    | #user-guide/consultation/methods/m19/:method-19
INFO    -    | #user-guide/consultation/methods/m2/:
INFO    -    | #user-guide/consultation/methods/m2/:diagram
INFO    -    | #user-guide/consultation/methods/m2/:equations
INFO    -    | #user-guide/consultation/methods/m2/:method-2
INFO    -    | #user-guide/consultation/methods/m3/:
INFO    -    | #user-guide/consultation/methods/m3/:diagram
INFO    -    | #user-guide/consultation/methods/m3/:equations
INFO    -    | #user-guide/consultation/methods/m3/:method-3
INFO    -    | #user-guide/consultation/methods/m4/:
INFO    -    | #user-guide/consultation/methods/m4/:diagram
INFO    -    | #user-guide/consultation/methods/m4/:equations
INFO    -    | #user-guide/consultation/methods/m4/:method-4
INFO    -    | #user-guide/consultation/methods/m5/:
INFO    -    | #user-guide/consultation/methods/m5/:diagram
INFO    -    | #user-guide/consultation/methods/m5/:equations
INFO    -    | #user-guide/consultation/methods/m5/:method-5
INFO    -    | #user-guide/consultation/methods/m6/:
INFO    -    | #user-guide/consultation/methods/m6/:diagram
INFO    -    | #user-guide/consultation/methods/m6/:equations
INFO    -    | #user-guide/consultation/methods/m6/:method-6
INFO    -    | #user-guide/consultation/methods/m7/:
INFO    -    | #user-guide/consultation/methods/m7/:diagram
INFO    -    | #user-guide/consultation/methods/m7/:equations
INFO    -    | #user-guide/consultation/methods/m7/:method-7
INFO    -    | #user-guide/consultation/methods/m8/:
INFO    -    | #user-guide/consultation/methods/m8/:diagram
INFO    -    | #user-guide/consultation/methods/m8/:equations
INFO    -    | #user-guide/consultation/methods/m8/:method-8
INFO    -    | #user-guide/consultation/methods/m9/:
INFO    -    | #user-guide/consultation/methods/m9/:diagram
INFO    -    | #user-guide/consultation/methods/m9/:equations
INFO    -    | #user-guide/consultation/methods/m9/:method-9
INFO    -    | #user-guide/data-consultation/:
INFO    -    | #user-guide/data-consultation/:data-consultation
INFO    -    | #user-guide/editor/:
INFO    -    | #user-guide/editor/:editor
INFO    -    | #user-guide/editor/edit0-species-edition/:
INFO    -    | #user-guide/editor/edit0-species-edition/:add-a-reactant
INFO    -    | #user-guide/editor/edit0-species-edition/:edit-a-reactant
INFO    -    | #user-guide/editor/edit0-species-edition/:edit-species
INFO    -    | #user-guide/editor/edit0-species-edition/:elements-information
INFO    -    | #user-guide/editor/edit0-species-edition/:fn:1
INFO    -    | #user-guide/editor/edit0-species-edition/:fnref:1
INFO    -    | #user-guide/editor/edit0-species-edition/:heat-capacities
INFO    -    | #user-guide/editor/edit0-species-edition/:other
INFO    -    | #user-guide/editor/edit0-species-edition/:reaction
INFO    -    | #user-guide/editor/edit0-species-edition/:remove-a-reactant
INFO    -    | #user-guide/editor/edit0-species-edition/:saving-species-editions
INFO    -    | #user-guide/editor/edit0-species-edition/:selected-data
INFO    -    | #user-guide/editor/edit0-species-edition/:sit-coefficients
INFO    -    | #user-guide/editor/edit0-species-edition/:species-information
INFO    -    | #user-guide/editor/edit0-species-edition/:thermodynamics
INFO    -    | #user-guide/editor/edit1-add-species/:
INFO    -    | #user-guide/editor/edit1-add-species/:adding-species
INFO    -    | #user-guide/editor/edit2-remove-species/:
INFO    -    | #user-guide/editor/edit2-remove-species/:removing-species
INFO    -    | #user-guide/editor/edit3-save/:
INFO    -    | #user-guide/editor/edit3-save/:saving-edited-json-file
INFO    -    | #user-guide/editor/edit4-recover/:
INFO    -    | #user-guide/editor/edit4-recover/:recover-data
INFO    -    | #user-guide/menu/:
INFO    -    | #user-guide/menu/:contents
INFO    -    | #user-guide/menu/:loaded-source
INFO    -    | #user-guide/menu/:main-bar
INFO    -    | #user-guide/menu/:xcheck-tools-menu
INFO    -    | #user-guide/menu/automation/:
INFO    -    | #user-guide/menu/automation/:automation
INFO    -    | #user-guide/menu/automation/:save
INFO    -    | #user-guide/menu/edition/:
INFO    -    | #user-guide/menu/edition/:edited-data
INFO    -    | #user-guide/menu/edition/:edition
INFO    -    | #user-guide/menu/edition/:exporting-track-changes
INFO    -    | #user-guide/menu/edition/:save-editions
INFO    -    | #user-guide/menu/edition/:species-added
INFO    -    | #user-guide/menu/edition/:species-removed
INFO    -    | #user-guide/menu/edition/:track-changes
INFO    -    | #user-guide/menu/file/:
INFO    -    | #user-guide/menu/file/:bibliographic-references
INFO    -    | #user-guide/menu/file/:excel-file
INFO    -    | #user-guide/menu/file/:exit
INFO    -    | #user-guide/menu/file/:export
INFO    -    | #user-guide/menu/file/:file
INFO    -    | #user-guide/menu/file/:fn:1
INFO    -    | #user-guide/menu/file/:fn:2
INFO    -    | #user-guide/menu/file/:fnref:1
INFO    -    | #user-guide/menu/file/:fnref:2
INFO    -    | #user-guide/menu/file/:import
INFO    -    | #user-guide/menu/file/:json-file
INFO    -    | #user-guide/menu/file/:oracle-database-connection
INFO    -    | #user-guide/menu/help/:
INFO    -    | #user-guide/menu/help/:about
INFO    -    | #user-guide/menu/help/:calculation-routes
INFO    -    | #user-guide/menu/help/:help
INFO    -    | #user-guide/menu/help/:user-guide
INFO    -    | #user-guide/menu/tools/:
INFO    -    | #user-guide/menu/tools/:excel-comparer
INFO    -    | #user-guide/menu/tools/:json-comparer
INFO    -    | #user-guide/menu/tools/:json-to-excel-converter
INFO    -    | #user-guide/menu/tools/:tools
INFO    -    | #user-guide/tcextract/:
INFO    -    | #user-guide/tcextract/:data-extraction
INFO    -    | #user-guide/tcextract/:extracting-from-data-source-loaded
INFO    -    | #user-guide/tcextract/:extracting-from-oracle-database-version
INFO    -    | #user-guide/tcextract/:input-options
INFO    -    | #user-guide/tcextract/:output-options
INFO    -    | #user-guide/tcextract/:output-path
INFO    -    | #user-guide/tcextract/:select-file
INFO    -    | #user-guide/tcextract/:tcextract
Traceback (most recent call last):
  File "C:\Users\dperez\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\dperez\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\dperez\root\web\mkdocs\mkdocs-xcheck-tool-v5.0\env\Scripts\mkdocs.exe\__main__.py", line 7, in <module>
  File "c:\users\dperez\root\web\mkdocs\mkdocs-xcheck-tool-v5.0\env\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\dperez\root\web\mkdocs\mkdocs-xcheck-tool-v5.0\env\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\dperez\root\web\mkdocs\mkdocs-xcheck-tool-v5.0\env\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\dperez\root\web\mkdocs\mkdocs-xcheck-tool-v5.0\env\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\dperez\root\web\mkdocs\mkdocs-xcheck-tool-v5.0\env\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\dperez\root\web\mkdocs\mkdocs-xcheck-tool-v5.0\env\lib\site-packages\mkdocs\__main__.py", line 133, in serve_command
    serve.serve(
  File "c:\users\dperez\root\web\mkdocs\mkdocs-xcheck-tool-v5.0\env\lib\site-packages\mkdocs\commands\serve.py", line 141, in serve
    config = builder()
  File "c:\users\dperez\root\web\mkdocs\mkdocs-xcheck-tool-v5.0\env\lib\site-packages\mkdocs\commands\serve.py", line 136, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "c:\users\dperez\root\web\mkdocs\mkdocs-xcheck-tool-v5.0\env\lib\site-packages\mkdocs\commands\build.py", line 295, in build
    config['plugins'].run_event('post_build', config=config)
  File "c:\users\dperez\root\web\mkdocs\mkdocs-xcheck-tool-v5.0\env\lib\site-packages\mkdocs\plugins.py", line 96, in run_event
    result = method(**kwargs)
  File "c:\users\dperez\root\web\mkdocs\mkdocs-xcheck-tool-v5.0\env\lib\site-packages\mkdocs_with_pdf\plugin.py", line 135, in on_post_build
    self.generator.on_post_build(config, self.config['output_path'])
  File "c:\users\dperez\root\web\mkdocs\mkdocs-xcheck-tool-v5.0\env\lib\site-packages\mkdocs_with_pdf\generator.py", line 132, in on_post_build
    print(html_string)
  File "C:\Users\dperez\AppData\Local\Programs\Python\Python38\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u21a9' in position 48560: character maps to <undefined>
```

**Comment by orzih** [comment]
> UnicodeEncodeError: 'charmap' codec can't encode character '\u21a9' in position 48560: character maps to <undefined>

This is a code conversion problem between `Windows-1252` and `Unicode`.
I'll be check it.

... and, can you try this?

```dos
$ set PYTHONUTF8=1
$ mkdocs build > debug_pre_pdf.html
```

refs: [PEP-0540](https://www.python.org/dev/peps/pep-0540/)

**Comment by darkonl** [comment]
Ok, I tryied to set the PYTHONUTF8 environment variable but still the same problem...I'll try to check it out later and reinstall everything and run the project again.

Thank you for your help @orzih !!

**Comment by darkonl** [comment]
I've recently installed Linux for working on other projects. I rebuild this particular MkDocs project in Linux and everything works perfect. I don't know what could have happened.
